[package]
name = "aoc2015"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
hex = "0.4.3"
md-5 = "0.10"
regex = "1.5.4"
aoc = { path = "../" }
lazy_static = "1.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
